manifests/extension.pp
spec/defines/extension_spec.rb

Add support to load pecl extensions as zend extensions

---

manifests/fpm/config.pp

Inspired by a similar option in the nginx module (vhost_purge).

Add fpm config parameter to purge pool dir

---

metadata.json

bump stdlib requirement to 4.2

---

.travis.yml
Gemfile
Rakefile
manifests/cli.pp
manifests/composer.pp
manifests/config/setting.pp
manifests/fpm.pp
manifests/fpm/config.pp
manifests/fpm/pool.pp
manifests/init.pp
manifests/params.pp
manifests/phpunit.pp
manifests/repo.pp
manifests/repo/debian.pp
manifests/repo/suse.pp

Comments please :newspaper:, there are two tests failing, maybe @globin has an idea about the inifile paramter, and I still have to think over the spaceship operator, as long as nobody else has a quick solution for that.

get closer to Puppet4 readyness

---

manifests/repo/ubuntu.pp
spec/classes/php_repo_ubuntu_spec.rb

+) added $php::repo::ubuntu::ppa
+) conflicts with $php::repo::ubuntu::oldstable

Support a custom/specific PPA for Ubuntu systems

---

manifests/fpm.pp
manifests/fpm/service.pp

Create upstart service override before installing php-fpm

---

metadata.json

change supported Puppet versions

---

manifests/init.pp

This was changed to "present" in d4785f65e10520b3cf2c30c850a9b2eaceb1d726

Fix documentation for php::ensure

---

README.md
metadata.json

For some history read this issue: https://github.com/mayflower/puppet-php/issues/118
And then read the comments in this PR that got closed without merge: https://github.com/mayflower/puppet-php/pull/137

Updated README.md with better examples

---

manifests/fpm/pool.pp

It would be great to be able to change the template used in the pool definition so I added this as an option that defaults to the included template file.
I also added an options hash which would also be handy when using a custom template.

Adding custom template option and options hash, fixing some formatting, aligning params

---

manifests/repo/ubuntu.pp

@mvisonneau @tdm4 could you have a look? From a quick glance, this should already be taken care of by the anchoring in init.pp.

remove superfluous requires

---

README.md
manifests/repo/ubuntu.pp
spec/classes/php_repo_ubuntu_spec.rb

Removes php::repo::ubuntu::ppa (Issue #214 )
Also removes reference to it in README.md

Remove php::repo::ubuntu::ppa

---

manifests/globals.pp
manifests/params.pp

add SuSE PHP 7.0 Support

---

manifests/params.pp

fix error when dealing with php_version on suse

---

lib/facter/phpversion.rb
lib/puppet/parser/functions/ensure_prefix.rb
lib/puppet/parser/functions/to_hash_settings.rb
lib/puppet/provider/package/pear.rb
lib/puppet/provider/package/pecl.rb
spec/classes/php_fpm_config_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_repo_ubuntu_spec.rb
spec/classes/php_spec.rb
spec/defines/config_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

There are some remaining - mainly in the providers code.  Some of these look a bit tricky, so I might do separate PRs for them.

Rubocop fixes

---

manifests/composer.pp
manifests/init.pp

We want to manage curl with different params like ensure => latest...
So ensure_packages no work for us.

Ability to manage my own curl

---

manifests/composer.pp
manifests/composer/auto_update.pp

additionally, we fix an issue with passing the environment.

*correctly* use voxpupuli/archive

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.gitignore
.msync.yml
.travis.yml
spec/default_facts.yml
spec/spec_helper.rb

modulesync 0.16.4

---

manifests/global.pp
manifests/init.pp

Expose global inifile variable

---

.msync.yml
.rubocop.yml
Gemfile
spec/classes/php_fpm_spec.rb
spec/spec_helper.rb

modulesync 0.16.10

---

manifests/repo/debian.pp

update deprecated apt::key parameters

---

.msync.yml
.travis.yml
CHANGELOG.md
metadata.json

@igalic is currently working on a fix for environment variables. This PR shall not be merged before his PR is merged.

Modulesync 0.16.11 & Release 4.0.0

---

README.md

Fixed forge badge on README.md

---

manifests/extension.pp

inspired by 8cb3fb573a3c6227f40daf3c04e04ec7d7d6fc42

don't try to load extension.so for pear modules

---

.github/CONTRIBUTING.md
.msync.yml
.overcommit.yml
.rubocop.yml
.travis.yml
Gemfile
lib/puppet/parser/functions/ensure_prefix.rb
lib/puppet/parser/functions/to_hash_settings.rb
manifests/composer.pp
manifests/embedded.pp
manifests/init.pp
manifests/phpunit.pp
manifests/repo/suse.pp
spec/classes/php_fpm_spec.rb
spec/classes/php_repo_ubuntu_spec.rb
spec/classes/php_spec.rb
spec/defines/config_spec.rb
spec/defines/fpm_pool_spec.rb

Modulesync 0.21.0

---

manifests/repo/redhat.pp
metadata.json

remove example42/yum dependency

---

manifests/extension.pp
manifests/extension/install.pp
types/installoptions.pp

extension: pass install_options to provider

---

manifests/extension.pp

(same fix on master will come later, need this on puppet 3 quickly)

pear/pecl: pass install_options to provider

---

manifests/globals.pp
manifests/params.pp
metadata.json
spec/classes/php_spec.rb
spec/defines/extension_spec.rb

add initial archlinux support

---

.sync.yml
.travis.yml
CHANGELOG.md
metadata.json

Deets in the changelog. I think I got everything?

Release 5.0.0

---

spec/unit/provider/package/pear_spec.rb

Similar change to https://github.com/voxpupuli/puppet-nodejs/pull/318
Not sure if there's a better or more efficient way.

Proposed fix for failing parallel spec tests

---

manifests/globals.pp

fix ubuntu 17.04 version for php7

---

manifests/globals.pp
manifests/params.pp

Change default RedHat params to use config_root

---

metadata.json

mark Puppet 5 as supported

---

manifests/dev.pp
manifests/pear.pp
metadata.json
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

This was mostly working, it just wasn't tested. I added the tests and fixed some edge cases.

add ubuntu 16.04 support

---

manifests/dev.pp

this fixes an error that was introduced in 0ad75666619af1e3b0b5723a93b5bf9acacf846d

use correct require arguments

---

.sync.yml
.travis.yml
spec/acceptance/php_spec.rb
spec/spec_helper_acceptance.rb

Add Acceptance tests

---

README.md

add examples for php-fpm/nginx

---

manifests/params.pp

Fix Archlinux support

---

metadata.json

Updated dependency check for puppet/archive
@alexjfisher there we go ;)

Update puppet/archive dependency

---

.travis.yml
manifests/globals.pp
metadata.json
spec/acceptance/php_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

Debian 9 support

---

manifests/repo/debian.pp

switch the dotdeb repo url to https

---

manifests/apache_config.pp
manifests/cli.pp
manifests/composer.pp
manifests/dev.pp
manifests/embedded.pp
manifests/extension.pp
manifests/extension/config.pp
manifests/extension/install.pp
manifests/fpm.pp
manifests/fpm/config.pp
manifests/fpm/pool.pp
manifests/fpm/service.pp
manifests/global.pp
manifests/init.pp
manifests/packages.pp
manifests/pear.pp
manifests/phpunit.pp
manifests/repo.pp

migrate vars from topscope to relative scope

---

manifests/apache_config.pp
manifests/cli.pp
manifests/composer.pp
manifests/composer/auto_update.pp
manifests/config/setting.pp
manifests/dev.pp
manifests/embedded.pp
manifests/fpm/config.pp
manifests/global.pp
manifests/packages.pp
manifests/pear.pp
manifests/phpunit.pp
manifests/phpunit/auto_update.pp
manifests/repo/debian.pp

mark private classes with assert_private()

---

.sync.yml
.travis.yml
spec/acceptance/php_spec.rb

enable ubuntu 18.04 acceptance tests

---

README.md

Update README.md with working RHSCL example.

---

.msync.yml
.travis.yml
Gemfile
metadata.json
spec/spec_helper_acceptance.rb

modulesync 1.9.5 / allow puppetlabs/apt 5.x

---

manifests/extension.pp
spec/acceptance/php_spec.rb

Add acceptance tests for system php with extensions

---

CHANGELOG.md
metadata.json

release 6.0.1

---

CHANGELOG.md
metadata.json

release 6.0.2

---

.sync.yml

Ubuntu 14.04 is End of Life. We already removed parts in https://github.com/voxpupuli/puppet-php/pull/519

Drop Ubuntu 14.04

---

manifests/repo/debian.pp

hotfix:: updating key id for debian repo sury

---

manifests/fpm.pp
manifests/init.pp
manifests/params.pp

Similar to the following stale PR: https://github.com/voxpupuli/puppet-php/pull/515/files

add pool_purge option to init.pp

---

README.md

Remove duplicate mysqlnd from example in README

Remove duplicate mysqlnd from example in README

---

data/default.yaml
manifests/init.pp
manifests/params.pp
spec/classes/php_spec.rb

This PR fixs #558 and let #557 to work as intended

remove www pool from defaults

---

manifests/globals.pp
metadata.json
spec/acceptance/php_spec.rb

Add support for Debian 11

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.github/workflows/release.yml
.msync.yml
.puppet-lint.rc
Dockerfile
Gemfile
Rakefile
lib/facter/phpversion.rb
lib/puppet/parser/functions/ensure_prefix.rb
lib/puppet/parser/functions/to_hash_settings.rb
lib/puppet/provider/package/pear.rb
lib/puppet/provider/package/pecl.rb
spec/acceptance/php_spec.rb
spec/classes/php_fpm_config_spec.rb
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_repo_spec.rb
spec/classes/php_repo_ubuntu_spec.rb
spec/classes/php_spec.rb
spec/defines/config_spec.rb
spec/defines/extension_rhscl_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb
spec/functions/to_hash_settings_spec.rb
spec/spec_helper.rb
spec/spec_helper_acceptance.rb
spec/unit/provider/package/pear_spec.rb
spec/unit/provider/package/pecl_spec.rb

modulesync 5.2.0

---

manifests/config.pp
manifests/extension/config.pp
manifests/globals.pp
metadata.json
spec/acceptance/php_spec.rb
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

Since the PR #658  to add support for Ubuntu 22.04 wasn't moving forward, I tried to get things moving.
This adds Ubuntu 22.04 support.
No open issue regarding this feature.

Add Ubuntu 22.04 support

---

LICENSE

Fix broken MIT license

---

CHANGELOG.md
metadata.json

Release 8.2.0

---

.msync.yml
Gemfile
manifests/extension/config.pp

modulesync 6.0.0

---

metadata.json

metadata.json: allow puppet/zypprepo 5.x

---

manifests/repo/redhat.pp

fix remi-php56 repo gpgkey file

---

.github/CONTRIBUTING.md
.github/labeler.yml
.github/release.yml
.github/workflows/labeler.yml
.github/workflows/release.yml
.msync.yml
.puppet-lint.rc
Gemfile
metadata.json
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_repo_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_rhscl_spec.rb
spec/defines/extension_spec.rb
spec/spec_helper.rb

Drop Ubuntu 18.04

---

metadata.json

allow puppetlabs/apt 10

---

manifests/composer/auto_update.pp
spec/classes/php_composer_spec.rb

Fix the environment variable as documented in curl(1)
Throw an error at the user if not correctly configured
See issue for the full explanation
Fixes #731

fix: set proxy environment variables correctly
