manifests/init.pp
manifests/params.pp
manifests/pear.pp

php::pear currently defaults to ensure "$php::ensure". This causes some
trouble once versions are specified as PHP could be on 5.6 and PEAR at 1.9.

Give PEAR it's own ensure.

---

manifests/extension.pp

Previously, only pecl provider was using the parameter pecl_source
which was a shame since pear provider also understands the source
parameter. This renames 'pecl_source' to 'source' and supplies it
to all providers.
Unfortunately this introduces an API change - not sure how to handle backwards compatibility. It would be possible to understand both source and pecl_source but it sounds quite hacky.
What do you think?

Use the extension 'source' parameter for all providers

---

.travis.yml
Gemfile
lib/puppet/parser/functions/to_hash_settings.rb
manifests/apache_vhost.pp
manifests/cli.pp
manifests/composer.pp
manifests/composer/auto_update.pp
manifests/config.pp
manifests/config/setting.pp
manifests/dev.pp
manifests/extension.pp
manifests/fpm.pp
manifests/fpm/config.pp
manifests/fpm/pool.pp
manifests/fpm/service.pp
manifests/init.pp
manifests/packages.pp
manifests/params.pp
manifests/pear.pp
manifests/phpunit.pp
manifests/phpunit/auto_update.pp
manifests/repo.pp
manifests/repo/debian.pp
manifests/repo/suse.pp
manifests/repo/ubuntu.pp

This adds documentation generation with puppetlabs-strings on travis-ci. The documentation is pushed to the local `gh-pages` branch and is served on https://mayflower.github.io/puppet-php/ and http://php.puppet.mayflower.de/.
The existing documentation was cleaned up. The authors and license sections and top-level headlines were removed because they're not needed with the default yard templates that puppetlabs-strings uses.

Generate & serve documentation

---

README.md
manifests/composer.pp
manifests/dev.pp
manifests/extension.pp
manifests/fpm.pp
manifests/fpm/config.pp
manifests/fpm/pool.pp
manifests/init.pp
manifests/params.pp
manifests/pear.pp
manifests/phpunit.pp
metadata.json
templates/fpm/php-fpm.conf.erb

This adds support for FreeBSD and handles the following differences:
* no 'fpm' package available (included in main PHP package)
* no 'devel' package available (also included in main PHP package)
* group 'root' is named 'wheel' on FreeBSD
* additional software is installed under '/usr/local'
* replace FreeBSD's system-wide `extensions.ini` with per-module configuration files
There are a few limitations though:
* no support for `manage_repos` on FreeBSD (not useful on this plattform)
* support for 'composer' and 'phpunit' is untested
Tested with the following hiera configuration:
```yaml
php::ensure: 'installed'
php::manage_repos: false
php::fpm: true
php::dev: true
php::composer: false
php::pear: true
php::phpunit: false
php::fpm::config:log_level: 'notice'
php::composer::auto_update: …
```

add support for FreeBSD

---

manifests/init.pp
manifests/params.pp
spec/classes/php_spec.rb

I was trying to pin to a specific PHP version and encountered some problems with the module.
This is the node data I was using (i.e. `common.yaml` in wasted):
```yaml
php::ensure: 5.5.9+dfsg-1ubuntu4.9
php::fpm::ensure: 5.5.9+dfsg-1ubuntu4.9
php::cli::ensure: 5.5.9+dfsg-1ubuntu4.9
php::manage_repo: false
component::php::manage_repo: true
component::php::repo::repo:
jenkins_php5.5.5.9:
key: F5067765
key_source: https://jenkins.example.com/php/PUBKEY.gpg
location: http://jenkins.example.com/php/
repos: main
include_src: false
```
This is supposed to pin to 5.5.9, but some modules have different versions than the PHP core (see commit message) resulting in a broken install (package/version not available).
I've worked around this by creating all extensions outside of the module and then …

$ensure handling for module and extensions

---

manifests/repo/redhat.pp

See:
https://github.com/example42/puppet-yum/blob/master/manifests/repo/remi_php56.pp#L5

Bugfix: changed - to _ to match default value yum::repo::remi_php56

---

lib/puppet/parser/functions/ensure_prefix.rb
manifests/extension.pp
spec/defines/extension_spec.rb

By default extension setting keys are now prefixed with `<name>.`
If the prefix is already present, nothing is changed.
This allows for simpler extension configuration by simply passing
the setting name without prefix.
Fixes #81

Ensure extension setting prefix

---

manifests/fpm/config.pp

Although it works anyway because `[smhd]` is optional in `interval_re`, `emergency_restart_threshold` is an integer and should be checked against `number_re` instead.
From [PHP documentation](http://php.net/manual/en/install.fpm.configuration.php):
```
emergency_restart_threshold int
If this number of child processes exit with SIGSEGV or SIGBUS within the time interval set by emergency_restart_interval then FPM will restart. A value of 0 means 'Off'. Default value: 0 (Off).
```

emergency_restart_threshold is number

---

manifests/fpm/pool.pp
templates/fpm/pool.conf.erb

The only way to open the service to any IP is to not include the `listen.allowed_clients` option in the pool. (Since I want to manage this through AWS security groups, it is still safe)
Can't set an empty value in YAML, apparently.
**WARNING**: This means a change in behaviour!!!
Those that set `listen` to something other than 127.0.0.1 and trust the default to allow only requests sourced from 127.0.0.1, will find this change allows requests from any source.

Remove pool's default listen_allowed_clients and add conditional in template

---

templates/fpm/pool.conf.erb

Some environment variables use special characters, such as urls, security tokens and 
passwords. This causes the fpm to hang if we dos not wrap with single quotes.

Wrap variables to handle special characters

---

manifests/fpm/config.pp
manifests/params.pp
templates/fpm/php-fpm.conf.erb

Allows for any value to be set for error_log, and adds configuration for syslog.ident and syslog.facility.
Fixes #95

Allow sending errors to syslog

---

manifests/fpm/pool.pp
templates/fpm/pool.conf.erb

Fpm pool accepts include option which include other files on tha pool.
This is useful to include enviroment variables on a different files by
example.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mayflower/puppet-php/103)

Add option to include config files on pool

---

manifests/repo/suse.pp

This is more related to a package doing things wrong, but anyway, I'm getting:
```
[...]
Notice: /Stage[main]/Php::Repo/Php::Repo::Suse/Exec[zypprepo-accept-key]/returns: (with --nodeps --force) Error: Subprocess failed. Error: RPM failed: Can't exec 'rpm' (No such file or directory).
[...]
Error: /Stage[main]/Php::Repo/Php::Repo::Suse/Exec[zypprepo-accept-key]: zypper --gpg-auto-import-keys update -y returned 4 instead of one of [0]
[...]
```

include /bin in suse path

---

manifests/fpm/service.pp

Ubuntu versions newer than precise support reload signals but that feature is disabled by the package maintainer because he builds packages with the same upstart config for precise, too.
But because we actually use reload, refreshing the service doesn't work correctly which leads to php-fpm child processes that never get killed. These processes prevent restarting php-fpm altogether. The only fix is manually killing them.
See https://bugs.launchpad.net/ubuntu/+source/php5/+bug/1242376 for reference.
This patch ensures that reloading is not used on precise and the reload signal USR2 is used for all other supported versions of Ubuntu by creating an upstart override file.
/cc @globin @exi

Fix reloading php-fpm on trusty & utopic

---

templates/fpm/pool.conf.erb

The php fpm failed to start if the configuration for a pool contains something like 
`env[FOOBAR] = `
So with this fix the defect configuration will be prevent.

Add check if value is empty in the pool.conf.erb template

---

manifests/params.pp

Repos work fine for the entire family of Debian-based systems.

Include repositories for osfamily Debian, not just wheezy

---

lib/facter/phpversion.rb

I guess only the `phpversion` fact is actually useful, but it's hacky.

PHP custom facts

---

manifests/fpm/config.pp
manifests/params.pp
templates/fpm/php-fpm.conf.erb

Include a option to configure the fpm pid file. As in some distros (and
pgp versions) the pid file on the init script changes, we need to
provide a way to the user override the fpm pid file.
For example, at RedHat (AmazonLinux) the php56 package leves at:
`
/var/run/php-fpm/php-fpm-5.6.pid
`
With this change, the Amazon Linux user with the php56 package should
configure on hiera the key:
```yaml
php::fpm::config::pid_file: /var/run/php-fpm/php-fpm-5.6.pid
```

Include fpm pid file configuration

---

manifests/config/setting.pp

With this change, config values can be removed entirely.
For example, this will remove the `date.timezone` configuration entry:
```puppet
settings => {
'Date/date.timezone' => undef
}
}
```

Allow removal of config values

---

lib/puppet/provider/package/pear.rb
manifests/pear.pp

I may be totally wrong here, but shouldn't this be set up before the packages are installed?
For me, package installation fails (on a completely fresh box) with the hint to use "pear channel-discover pear...." to initialize or pear config-set auto_discover 1".

Make sure auto_discover is set *before* installing packages

---

manifests/embedded.pp
manifests/init.pp
manifests/params.pp

Support for embedded sapi - configuring specific for sapi `php.ini` as it is only thing I think is needed in this case.
Checked on RedHat and Debian. Fingers crossed for Suse & FreeBSD.

Embedded SAPI support (php.ini)

---

manifests/extension.pp

See #126 for the initial request.
I did a quick check and did not find any cross-class assumptions or dependencies, so this should be a safe change.

Make the ::php::extension module part of the public API

---

manifests/extension.pp

The `php5query` command needs a SAPI. We use `cli` here and hope that all extensions are managed for all SAPIs consistently.

Enable extension when package already installed

---

.travis.yml
metadata.json

Ruby 2.2 is only supported with Puppet 4.x. The PE version_requirement is open ended for now because of the 2015.x.x thing...

test Ruby 2.2 and Puppet 4

---

README.md

Makes sense to have this in the README as I had to dig in source code to find how to specify an alternate PPA, this was to use PHP 5.6.

add details of PPA override

---

lib/puppet/provider/package/pecl.rb

This PR:
- Discards header lines of the output of pecl list that are emphasized with coloration
- Pecl does case-insensitive searches so downcases pecl package names to always match
Bold font in the shell output of `pecl list` caused the regex checks to fail. In addition, `pecl list` capitalized some values causing the `==` check to fail. To fix we downcase. This was tested with APC on CentOS.

Fixes pecl provider

---

manifests/fpm/config.pp
manifests/fpm/pool.pp
templates/fpm/php-fpm.conf.erb
templates/fpm/pool.conf.erb

We manage a couple configuration options that aren't set in the current templates. Added the following options:
In php-fpm.conf, you can now modify process.max, and rlimit_files at this global level.
In the pool template, you can now modify the access log path and format.

Add options to fpm config and pool configs

---

manifests/repo/redhat.pp

have added the yum repo so this works ok on centos7 - not sure if i should leave the original reference in so have left it.

Fix for  php 5.6 on Centos 7.1.1503 #131 

---

manifests/extension.pp
manifests/fpm/pool.pp
manifests/init.pp
manifests/params.pp
spec/defines/extension_spec.rb

When I have tried to install the recently released PHP 7.0.0, I have come across some issues:
1. The path for FPM pool conf files are built with `$::php::params::fpm_pool_dir` instead of `$::php::fpm::config::pool_base_dir`. This makes impossible to override the path of these files, but this path can be overriden with previous parameter from class `php::fpm::config`, and that path should be used because the pools belong to FPM and should use its base dir.
2. The path for PHP extensions ini files are built with `$::php::params::config_root_ini`, and we have the same previous problem: it is impossible to override that path. This should be a parameter from the defined type `php::extension`, but it would not be *hierable* due to the intrinsic nature of the defined type. The best approach I …

Fixes non-overridable paths

---

manifests/fpm.pp
manifests/fpm/service.pp
manifests/init.pp
manifests/params.pp

We use supervisor to manage individual fpm services, but still want the php module to install php-fpm. Currently its not possible to ensure that the service is disabled and stopped.

Make it possible to enable/disable the fpm service.

---

manifests/fpm.pp
manifests/init.pp

Added possibility to override fpm service name in case of using php7.0
Resolves:  GH-161

Enable Override of $fpm_service_name in case of using php7.0

---

manifests/fpm.pp
manifests/init.pp

Given we'd rather not override this via specific parameters - we're making it possible to pass in the user/group on the root class

Allowed setting the FPM user from the root class

---

README.md

either module has to be changed or the documentation.
I would change module instead, since it's not intuitive, but this would create an incompatibility with current configurations

class uses 'pools' hiera key, not 'pool'

---

manifests/extension.pp
manifests/init.pp
manifests/params.pp
manifests/repo/ubuntu.pp

This fixes some issues with php7 and php5enmod/php5query on at least Ubuntu, but i assume it would also work on debian. 
Also switched to non deprecated php 7 repo.

Enable/Disable $ext_tool Debian

---

manifests/composer/auto_update.pp

FreeBSD installs all software from a package manager into `/usr/local`.
This includes the `wget` binary, which is included in the `pkg` package manager.
OSX will probably also benefit from this when `wget` is installed using Homebrew.

Add '/usr/local' paths to support FreeBSD

---

manifests/fpm.pp

Parameter $global_pool_settings for class ::php::fpm realize feature default global settings for all fpm pools.
Not used parameter (hiera example):
```
php::fpm::pools:
first_pool:
pm_min_spare_servers: '5'
pm_max_spare_servers: '35'
pm_max_requests: '2048'
ping_response: 'pong'
request_terminate_timeout: '120'
request_slowlog_timeout: '30'
rlimit_files: '2048'
catch_workers_output: 'no'
second_pool:
pm_min_spare_servers: '10'
pm_max_spare_servers: '35'
pm_max_requests: '2048'
ping_response: 'pong'
request_terminate_timeout: '120'
request_slowlog_timeout: '30'
rlimit_files: '2048'
catch_workers_output: 'no'
```
Used parameter (hiera example):
```
php::fpm::global_pool_settings:
pm_max_spare_servers: '35'
pm_max_requests: '2048'
ping_response: 'pong'
request_terminate_timeout: '120' …
```

Add third argument 'global_pool_settings' for resource ::php::fpm::pool.

---

README.md
manifests/extension.pp

This patch enables specifying a specific sapi to the php5enmod executor. Some extensions (i.e. php5-suhosin-extension) are undesirable for the cli sapi, and this enables specifying only fpm.

Allow specifying the sapi for debian/ubuntu systems

---

manifests/init.pp
spec/classes/php_spec.rb

#132 resulted in a global php.ini being created/managed to fix some issues on RedHat based systems.
Debian (and derivatives) don't actually have an `/etc/php|php5/php.ini`. All configuration lives under a SAPI. Configuring these settings in this global file does nothing under this family of operating systems.
I came across this when I noticed an ordering issue - settings in this file were trying to be managed _before_ the PHP packages were being installed, and as such `/etc/php5` didn't exist (see #191)
This PR stops managing the file, but doesn't clean it up on systems that might already have it. I didn't feel that was safe.

Don't manage global php.ini settings on Debian based systems

---

manifests/extension.pp

Hi,
puppet throws some warnings in the puppetserver.log (using 4.5.1), if puppet managed php an this host.
```
WARN  [qtp1416189715-65] [puppetserver] Puppet Arguments to Resource[] are all empty/undefined at /etc/puppetlabs/code/environments/productions/modules/php/manifests/extension.pp:99:13
```
I added a empty condition to define dependencies, if the header or compiler packages are required.

Avoid puppets warning in puppetserver.log

---

README.md
manifests/dev.pp
manifests/globals.pp
manifests/packages.pp
manifests/pear.pp
manifests/repo/ubuntu.pp
spec/classes/php_fpm_config_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_repo_ubuntu_spec.rb
spec/classes/php_spec.rb
spec/defines/config_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

Hi,
I've been doing work to get mayflower-php working with the ondrej-php PPA. It appears ondrej/php5 and ondrej/php5.6 are now deprecated and he has combined PHP 5.5, 5.6 and 7.0 into one repo. This completely breaks the module as it currently is. I've also put in some fixes so that it actually adds the PPA before it even tries to install the packages (in packages.pp, pear.pp and dev.pp).
Please test and let me know if all works as it should. I've tested it on Ubuntu 14.04 (Trusty) with versions 5.5, 5.6, and 7.0 with the PPA.

Ondrej-php PPA fixes/enhancements for Ubuntu

---

manifests/fpm.pp
manifests/fpm/service.pp
manifests/params.pp

closes GH-184
The lsb usage in the tests can stay as-is, as we do get lsb facts always in the facterdb provided facts.

stop using LSB facts

---

manifests/dev.pp
manifests/pear.pp
spec/classes/php_spec.rb

set as parameter to init.pp to some non-default
Also spec for xml package
add spec test for package_prefix
I'm in the phase of updating the php module, to get the
better php 7 support. Some of the boxes run on Ubuntu.
They have php 5.5 installed, and I don't want to upgrade
just because of the puppet php module update ;)
So besides other parameters, I set the package_prefix to 'php5-'
The only package that doesn't seem to catch that up is the php-xml
package, enforced via the php::dev class.
This PR also lets the xml package pick the right prefix, as well
as adding a bunch of spec tests, for ensuring correct functionality.

Fixup naming of xml package for Ubuntu, when the package_prefix is

---

manifests/fpm.pp
manifests/fpm/service.pp
manifests/init.pp

to allow using non-default service provider for fpm.
I'm on ubuntu 14.04, where the fpm service provider
picks init as default, but it should use upstart.
The default for the service_provider are all set to 
undef, so it picks whatever is default, as it currently
is, only allows the user to override to whatever provider
he wants to use.

Allow to specify a fpm_service_provider,

---

manifests/fpm.pp
manifests/globals.pp
manifests/params.pp
templates/fpm/php-fpm.conf.erb

allow of passing a pid file to globals like so:
```puppet
class { '::php::globals':
php_version => '5.5',
fpm_pid_file => '/var/run/php-fpm/php-fpm-5.5.pid',
} ->
ensure       => latest,
manage_repos => false,
fpm          => false,
dev          => false,
composer     => false,
pear         => true,
phpunit      => false,
}
```
This was need to address amazon linux and a init.d pid file looking for:
`pidfile=${PIDFILE-/var/run/php-fpm/php-fpm-5.5.pid}`

allow for class to be defined and pass a pid file path

---

manifests/extension.pp

Bug: phpquery command always exits with status code 0, even if the extension is not enabled, so the enable command is never run.
Fix: grep the string stating the extension is not enabled, and only run the enable command if that string is found

Fix command to enable php extensions

---

lib/puppet/parser/functions/ensure_prefix.rb
lib/puppet/parser/functions/to_hash_settings.rb
lib/puppet/provider/package/pear.rb
lib/puppet/provider/package/pecl.rb

Rubocop fixes

---

lib/puppet/provider/package/pecl.rb

Pipe was being set previously, 2 commits back, but then not used so rubucop complained.  1 commit back, pipe was then changed to being compared, which broke it because it was never set.  This fixes that to remove the variable `pipe` altogether since we only use @resource[:pipe] once and don't need a variable for it.  Brings it in line with things like @resource[:source]
Fixes #242

Pipe was broken in the previous rubucop fix

---

.fixtures.yml

Previously this was frozen to 1.8.x, released about 18 months ago.

fixtures: don't pin puppetlabs-apt version

---

manifests/dev.pp
manifests/globals.pp
manifests/params.pp
manifests/pear.pp
metadata.json
spec/classes/php_fpm_config_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

Fix for Ubuntu 14.04 Php installation:
Summary:
* The currents rule only work for PPA. Using 14.04 Official Ubuntu repository does not match any of the rules. 
* Removed 14.10 from metadata. It is in EOL and thing can randomly break. 
* Removed 12.04 from metadata. Default installation is 5.3, this module won't support any of it

Update module Ubuntu 14.04 default to official repository setup

---

manifests/extension.pp
spec/defines/extension_spec.rb

This fixes an issue where setting `source => 'none'` to a `php::extension` resource results in the following error:
```
Error: Could not find dependency Package[undef] for Php::Config[json] at /etc/puppet/modules/php/manifests/extension.pp:190
```

Fix dependency for extentions with no package source

---

manifests/extension.pp
spec/defines/extension_spec.rb

Thanks to [chrisboulton](https://github.com/chrisboulton), see https://github.com/voxpupuli/puppet-php/pull/193
https://github.com/voxpupuli/puppet-php/pull/54 (and https://github.com/voxpupuli/puppet-php/issues/52) added support for Zend extensions, but as stated only allows them for PECL installed extensions. I don't think this is the right behavior, so this PR removes that restriction and allows any extension to be designated as a Zend extension.
Take for example Xdebug, which is packaged as php5-xdebug on Debian. Xdebug WANTS to be loaded as a Zend extension, and won't work otherwise.
This PR is pretty opinionated in that it uses php::config to enforce either an extension or zend_extension value to be put into the mods-available configuration. Previously these lines were only managed …

Allow packaged extensions to be loaded as Zend extensions (bis)

---

manifests/extension.pp
spec/defines/extension_spec.rb

Take for example Xdebug, which is packaged as `php5-xdebug` on Debian. Xdebug _WANTS_ to be loaded as a Zend extension, and won't work otherwise.
This PR is pretty opinionated in that it uses `php::config` to enforce either an extension or zend_extension value to be put into the mods-available configuration. Previously these lines were only managed for PECL extensions, or on FreeBSD. I don't see a reason to not do it for all extensions. This doesn't seem to cause any issues for me, but it'd be great to get some additional thought on the implications of this change.

Allow packaged extensions to be loaded as Zend extensions

---

manifests/composer.pp
manifests/composer/auto_update.pp
manifests/init.pp

We need to download composer through a web proxy.
wget is broken when it comes to downloading through a proxy and using https, so we also need to switch to curl to achieve this.
Maybe we should eventually switch to the archive module for this? In any case this seems to work well for now.

Support using an http proxy for downloading composer

---

manifests/apache_config.pp
manifests/init.pp
manifests/params.pp

I'd like to be able to manage the php.ini file (and extensions) used by apache/mod_php since I have some applications that can't be easily converted to using php-fpm.
This lacks configuration parameters for Suse and BSD, but I'm hoping that someone will be able to chime in and I'll add them.

Manage apache/PHP configurations

---

.fixtures.yml
manifests/composer.pp
manifests/composer/auto_update.pp
manifests/init.pp
metadata.json

rather than using a hand-crafted curl call, we use voxpupuli/archive to
download composer. This has the benefit that it doesn't require us to
$manage_curl. But we also remove `$environment`! This variable name is
poorly chosen. Overriding it (or even just setting it to `undef`), could
mean that someone's `hiera()` lookups are failing, as soon as they enter
our module!
This pull-request addresses #273.

use voxpupuli/archive to download composer

---

manifests/packages.pp

PR #250 introduced code that unconditionally includes `::apt`. This should be changed to respect wether `$manage_repos` is actually set to `true` or not.
Otherwise I'm unable to use my own repo management, because the include leads to a duplicate declaration:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Class[Apt] is already declared
```

respect $manage_repos, do not include ::apt if set to false

---

manifests/extension.pp

cf https://github.com/voxpupuli/puppet-php/blob/master/lib/puppet/provider/package/pecl.rb#L83

allow pipe param for pecl extensions

---

lib/puppet/provider/package/pear.rb
lib/puppet/provider/package/pecl.rb
manifests/extension.pp
spec/defines/extension_spec.rb
spec/fixtures/unit/provider/package/pear/list_a
spec/fixtures/unit/provider/package/pear/remote-info_benchmark
spec/fixtures/unit/provider/package/pear/remote-info_zip
spec/unit/provider/package/pear_spec.rb
spec/unit/provider/package/pecl_spec.rb

could return info about another package
example:
```
pry> @resource
=> Package[pecl-mongo]
pry> self.class.pecllist(justme: peclname)
=> {:name=>"pecl-apcu", :ensure=>"4.0.7", :provider=>:peclcmd}
```
this wrongly results in pecl-mongo not being installed when needed
fixes #255 as well by returning the correct version for installed
packages

fix pecl/pear providers query method

---

manifests/composer/auto_update.pp

we were passing a Hash, a Hash missing HOME, at that (#303)
This fixes both issues.

composer auto_update: exec's environment must be array

---

manifests/repo/ubuntu.pp

PHP 5.5 on Ubuntu is no longer available for download from the "ondrej/php" PPA. I think we should fail the execution when people want to install it.

Remove support for PHP 5.5 in Ubuntu

---

manifests/extension.pp

We don't need the overly complex ensure_packages() function.
This module is designed to manage php. We should be confident in this,
and just let it do that.

replace ensure_packages use with package resource

---

manifests/extension.pp

the current behaviour will generate the following output on every php-cli action (including every cronjob)
```
Warning: Could not match PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/Image_Canvas.so' - /usr/lib/php/20131226/Image_Canvas.so: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: Could not match PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/Image_Color.so' - /usr/lib/php/20131226/Image_Color.so: cannot open shared object file: No such file or directory in Unknown on line 0
Warning: Could not match PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/Image_Graph.so' - /usr/lib/php/20131226/Image_Graph.so: cannot open shared object file: No such …
```

no further config required for PEAR extensions

---

manifests/extension.pp
manifests/extension/config.pp
manifests/extension/install.pp
types/provider.pp
types/sapi.pp

This defined type tried to do too much at once, so split the two main
concerns: installation & onfiguration.
Readability is greatly enhanced by reducing the nesting level of `if`s.

Simplify php::extension

---

manifests/extension/config.pp
spec/defines/extension_spec.rb

previously we placed extensions= directives in their $so_name.ini
This behaviour is now restored.

php::extension: restore prev behaviour wrt extension.ini naming

---

README.md
manifests/fpm.pp
manifests/init.pp
spec/classes/php_spec.rb

Hey there,
The fpm user and group are not currently overridable outside of Hiera. This propagates the fpm user and group similarly to log_owner and log_group.
Redhat systems default the user to apache, but we're using nginx.
Let me know if this needs anything else. Thanks!

expose fpm user and group

---

manifests/packages.pp

The change introduced in #278 seems reasonable, but it means that `Class['apt::update']` may not actually be defined.

Only add a dependency on `Class['apt::update']` if `$manage_repo` is `true`

---

manifests/repo/debian.pp
metadata.json

This adds support for the latest puppetlabs-apt module. The parameter in apt::source changed, this got adjusted. The API of this module doesn't change, this is "only" a major version bump for one of the dependencies.

Add support for puppetlabs/apt 4.X

---

manifests/dev.pp
manifests/embedded.pp
manifests/extension/config.pp
manifests/fpm.pp
manifests/fpm/pool.pp
manifests/fpm/service.pp
manifests/globals.pp
manifests/init.pp
manifests/packages.pp
manifests/params.pp
manifests/pear.pp
manifests/repo.pp
manifests/repo/redhat.pp

replace legacy facts with new $facts hash

---

manifests/globals.pp

Hi,
this simple patch made installation of PHP 7.1 work for me on Debian 8 Jessie with manually configured  https://deb.sury.org/ repositories.
cheers
amette

Allow installing PHP 7.1 on Debian

---

manifests/extension.pp
manifests/extension/config.pp
spec/defines/extension_spec.rb

Hey there,
So when loading extensions, sometimes it's desirable to specify the extension load order — for example loading opcache before other modules. This adds support for prefixing the extension ini filename to accomplish this.

Add optional param to prefix the extension ini filename

---

manifests/repo.pp
spec/classes/php_repo_spec.rb

This fixes #373 where where Debian repositories were being
selected on Ubuntu systems.

Fix OS facts usage when selecting repo class for Ubuntu systems

---

manifests/fpm.pp
manifests/fpm/service.pp
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb

This change uses `versioncmp` instead of an equality operator when
comparing Ubuntu OS facts for more compatibility between various facter
versions, and Ubuntu system versions.
Also, `$facts['os']['release']['major']` was changed to
`$facts['os']['release']['full']` to be more consistent with other
version comparisons in this module.
Fixes the issue reported in #372.

Fix OS fact comparison for Ubuntu 12 and 14

---

metadata.json

This small PR only bumps the dependency on puppet/archive to `< 3.0.0`. The only breaking change in the new 2.0.0 series is the switch to puppet4 types, which has also been done in puppet/php, so no changes are necessary.

bump dep on puppet/archive to '< 3.0.0'

---

types/provider.pp
types/sapi.pp

```
Error: Syntax error at ']' at /etc/puppetlabs/code/modules/php/types/sapi.pp:6:1
Error: Syntax error at ']' at /etc/puppetlabs/code/modules/php/types/provider.pp:28:1
```

Fix syntax issues with data types

---

lib/puppet/provider/package/pecl.rb

Confine pecl provider to where pear command is available

---

manifests/repo/redhat.pp
metadata.json

Hi 
This is a backport of #355 for the puppet3 branch. I directly cherry-picked the commits and for me it seems to work.
BTW doesn't #355 fixes https://github.com/voxpupuli/puppet-php/issues/284 too?

Backport of #355  remove example42/yum dependency on puppet3 branch

---

manifests/pear.pp

When the pear package name is defined, it is based on `$facter['os']['family']`. The problem is that Amazon Linux has 'RedHat' as os family.
I set an `if` before case searching for 'Amazon' in `$facter['os']['name']` based on the output of the facter command on Amazon instances:
```shell
$ facter os
{
architecture => "x86_64",
family => "RedHat",
hardware => "x86_64",
name => "Amazon",
release => {
full => "2017.09",
major => "2017",
minor => "09"
},
selinux => {
enabled => false
}
}
```
Extra information:
Puppet agent version: _4.10.1_
facter version: _3.6.4_
AMI Releas: _Amazon Linux AMI 2017.09.0.20170930 x86_64 HVM EBS_

Fixing wrong pear package name in Amazon Linux

---

manifests/globals.pp
manifests/repo/debian.pp
metadata.json
spec/classes/php_repo_spec.rb

I've added support for PHP 7.1 on Debian (jessie, stretch).
```
PHP 7.1.0-5+0~20161222133327.13+jessie~1.gbp46a191 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.1.0-5+0~20161222133327.13+jessie~1.gbp46a191, Copyright (c) 1999-2016, by Zend Technologies
with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```
I'm not sure if it's the most elegant way to install the required packages and how to avoid name conflicts.
Feedback is welcome.

Add PHP 7.1 support on Debian

---

manifests/composer/auto_update.pp

This fixes #402.
In case ```max_age``` has passed but no update was available we attempted to update on every run.

fix composer auto_update idempotency in case no update is available

---

manifests/repo/ubuntu.pp

software-properties-common is needed to add ppas on ubuntu. the
puppetlabs-apt module can manage the package. it is save to enable this,
because the module uses ensure_package: https://github.com/puppetlabs/puppetlabs-apt/blob/df40baebedf5c0c15e08f3ec78adfd760b1371ca/manifests/ppa.pp#L30
Without this, managing ppa repos at least on ubuntu 16.04 is impossible. I noticed this bug while testing with aceptance tests in https://github.com/voxpupuli/puppet-php/pull/418

manage software-properties-common on ubuntu

---

manifests/repo/debian.pp

This PR fixes a naming issue in php::repo::debian. The parameters given to the apt::key and apt::source defined types are not valid for the puppetlabs/apt module >= 4.4.0, which this module depends on.

Fix wrongly named parameters for apt::source/key

---

.sync.yml
.travis.yml
spec/acceptance/nodesets/docker/ubuntu-16.04.yml
spec/acceptance/php56_spec.rb
spec/acceptance/php_spec.rb

add tests for php5.6

---

manifests/repo/debian.pp

adde PR for https://github.com/voxpupuli/puppet-php/pull/420#pullrequestreview-100970274

Using the new facts hash instead of the global var in repo/debian.pp

---

.fixtures.yml
README.md
manifests/cli.pp
manifests/extension.pp
manifests/fpm.pp
manifests/fpm/config.pp
manifests/globals.pp
manifests/params.pp
spec/classes/php_fpm_config_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_rhscl_spec.rb
spec/defines/extension_spec.rb

This is a rebased version of #292 
Original text:
This adds RedHat SCL compatibility to this puppet module
by adding the rhscl_mode parameter to ::php::globals. By
specifying this parameter the module itself configures
path specifications on its own based on the php_version
string. Further the ::php::extensions define was extended
by the ability to prefix configs and stack up extensions
which are merged into one os package.

Compatibility with Software collections (SCL)

---

manifests/init.pp

fixed merge bug

---

manifests/extension/config.pp
spec/acceptance/php_spec.rb

When the extension has no module associated (e.g. with net-curl), the
module always run phpenmod command (because phpquery always report that
the module is not matched).
This commit tries to fix this problem

Fix enable extension when there is no module associated

---

.msync.yml
Gemfile
spec/classes/coverage_spec.rb
spec/default_facts.yml
spec/spec_helper.rb

modulesync 2.2.0

---

manifests/extension/config.pp

`ensure` parameter could also have the value `latest`, so this commit consider this
case.

ensure could also be 'latest'

---

manifests/fpm/pool.pp

The pool config does not need to be readable by others. This allows putting secrets into the files, without them being exposed. It might make sense to make this configurable.

Remove readable for others on pool config file

---

manifests/fpm/pool.pp
templates/fpm/pool.conf.erb

Allow `clear_env` to be disabled for PHP-FPM pool definitions.

Allow `clear_env` to be disabled

---

manifests/repo/debian.pp

This refactors the code to rely more on puppetlabs-apt features. It passes in the key and lets apt::source define apt::key for us.
Puppetlabs-apt also knows better when apt-transport-https is actually needed. On the most recent Debian/Ubuntu releases it doesn't even exist anymore since apt handles it out of the box.
It also removes the absolute resource notation which is no longer needed.

Rely more on puppetlabs-apt

---

manifests/repo/ubuntu.pp

Patch versions of PHP like version 7.1 do not install on Ubuntu 16.04 even though these versions are in the PPA.
Fixes the installation of minor patch versions for Ubuntu.

Fixed repositories managed for all patch version of 7.x for Ubuntu.

---

manifests/extension.pp
manifests/extension/install.pp
spec/acceptance/php_spec.rb

Fix eternal reload for mysqli and simplexml extension. 
Package name for mysqli extension is php7.2-mysql. Package name for simlexml extension is php7.2-xml. I can use package_prefix variable, than i add package_name variable with higher priority.
Example of configuration:
```puppet
ensure       => latest,
manage_repos => false,
pear         => true,
composer     => false,
fpm          => false,
dev          => false,
extensions   => {
bcmath    => {},
curl      => {},
gd        => {},
mbstring  => {},
simplexml => {
package_name => 'php7.2-xml',
},
mysqli    => {
package_name => 'php7.2-mysql',
},
sqlite3   => {},
},
}
```
Fixes #309 
Fixes #497

Fix php::fpm eternal reload for mysqli a simplexml extension

---

manifests/init.pp
spec/classes/php_spec.rb

Adds ``cli_settings`` parameter to ``::php`` class to allow specific settings for PHP CLI's php.ini file.
For example this allows you to specific 256M memory_limit for PHP and PHP-FPM but increase the limit for PHP CLI, ie, PHP scripts running detached from the a web browser, like:
```
class profile::php {
ensure       => latest,
manage_repos => false,
fpm          => true,
dev          => true,
composer     => true,
pear         => true,
phpunit      => false,
settings => {
'PHP/max_execution_time' => '60',
'PHP/memory_limit'       => '256M',
},
cli_settings => {
'PHP/memory_limit'       => '1000M',
},
}
}
```
Then the ``memory_limit`` would be set to ``256M`` in ``/etc/php.ini`` and ``/etc/php-fpm.ini`` and ``1000M`` in ``/etc/php-cli.ini`` on CentOS 7.
Fixes #489

Add cli_settings parameter to php class

---

.travis.yml
manifests/extension/config.pp
metadata.json
spec/defines/extension_spec.rb

PHP 7.0+ packaged with Ubuntu does not ship with mysql.so, and enabling the module should not setup a mysql.ini file referring to it.
This is an adaptation of #330 which has been stale for some times…
Fixes #330

Do not manage mysql.ini when using Ubuntu repo (and fix CI)

---

data/default.yaml
hiera.yaml
manifests/apache_config.pp
manifests/cli.pp
manifests/embedded.pp
manifests/fpm.pp
manifests/init.pp

Fix deprecated Hiera lookup warnings. Add YAML structure for default www pool so it can be overridden as needed.

Fix deprecated Hiera lookup warnings. Add default www pool in YAML.

---

manifests/extension.pp
spec/classes/php_spec.rb

This PR enables simplified removal of php. Without this change you have to set each extension the ensure attribute itself because php::ensure: absent will currently not influence php::extension::$title::ensure.

Simplify php (extension) removal

---

manifests/globals.pp
manifests/params.pp
metadata.json
spec/acceptance/php_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

debian buster was released on july 6th and many folks are already
deploying it. This module should start supporting the new debian stable
version.
For this, we need the module to know what the new default PHP version is
for this new release.
Closes: #529

set default version for debian buster and add support for buster

---

manifests/apache_config.pp

Trying to use the apache_config class to apply settings to the apache
SAPI fails with an error caused by a duplicate variable definition:
```
Error while evaluating a Resource Statement, Evaluation Error: Cannot reassign variable '$real_settings' (file:
/etc/puppetlabs/code/environments/development/modules/php/manifests/apache_config.pp, line: 18, column: 18)
```

fix "cannot redefine $real_settings" error

---

README.md
data/default.yaml
manifests/fpm.pp

When allowing configuring `php::fpm::pools` as hashes in Hiera, the `unique` ("array merge") behavior is currently used. [Documentation](https://puppet.com/docs/puppet/6.4/function.html#merge-behaviors) states this will return a merged array even though we are interested in a hash. Instead of doing this manual lookup, we can switch to auto lookups.
Fixes #536

Do a `deep` merge on `fpm` lookup

---

manifests/packages.pp

Fix os::family name for Debian.
Fix running apt update on Debian family.
Replace 'debian' by 'Debian' in family check in accordance with Facter family name constants: https://github.com/puppetlabs/facter/blob/2aa2d1cd6487f73fb8e311cf027dcf30c2166e28/lib/inc/facter/facts/os_family.hpp

Fix running apt update on Debian family

---

.github/CONTRIBUTING.md
.msync.yml
.rubocop.yml
.sync.yml
.travis.yml
Dockerfile
Gemfile
Rakefile
manifests/fpm.pp
manifests/global.pp
manifests/init.pp
manifests/packages.pp
manifests/pear.pp
manifests/repo.pp
manifests/repo/ubuntu.pp
spec/acceptance/php_spec.rb
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/spec_helper.rb
spec/unit/provider/package/pear_spec.rb
spec/unit/provider/package/pecl_spec.rb

modulesync 2.12.0 and drop puppet 4

---

REFERENCE.md
manifests/composer.pp
manifests/composer/auto_update.pp
types/composerchannel.pp

Yesterday, composer released 2.0 snapshot.
So with current default behaviour, if i only set
`class { '::php::composer':
max_age => 2,
}`
every composer installation is updated to version 2.0 snapshot.
So one solution is to set the 'source' to 'https://getcomposer.org/composer-stable.phar' initialy if i dont have it installed or use the param from this PR for updates, which then defaults update channel to 'stable'

add ability to define composer update channel

---

manifests/globals.pp
manifests/params.pp
manifests/pear.pp

On FreeBSD, the package prefix is currently hardcoded to php56. This change modifies the default behaviour to use the prefix matching the selected php version (from globals) if defined.
This change should be fully compatible, since the default is to fallback to php56, and if a custom version is specified, the package prefix has to be manually configured to match this version anyway.
Futhermore, the pear package is now using a php prefix as well (since 2018-03-08), which is also fixed by this pull request.

Improve package prefix selection on FreeBSD

---

manifests/extension/config.pp
spec/defines/extension_spec.rb

Zend extensions are not enabled on Debian because `phpenmod` is not executed.  Same patch as stalled PR 498 with a test added.
n/a

Fix enabling of zend extensions

---

manifests/fpm/config.pp

This pull request cleans up the fpm config class:
- Remove unused variable 'log_group_final'
- Fixes owner, group and mode for the directories '/var/log/php-fpm' and '/var/run/php-fpm'
/var/log/php-fpm:
We don't know which processes want to access this directory - therefore root with mode 0755 is used here. This is also the default within most distributions.
/var/run/php-fpm:
There is no need to set the PHP-FPM user/group as a owner of this directory. This is also follows the default within most distributions.
Fixes #568

Cleanup fpm config class

---

.fixtures.yml
manifests/dev.pp
manifests/fpm.pp
manifests/fpm/service.pp
manifests/globals.pp
manifests/repo/debian.pp
manifests/repo/ubuntu.pp
metadata.json
spec/classes/php_fpm_config_spec.rb
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_repo_spec.rb
spec/classes/php_repo_ubuntu_spec.rb
spec/classes/php_spec.rb

Drop EOL Debian 7/8 & Ubuntu 12/14

---

manifests/fpm/service.pp

Some configuration options (e.g. 'listen_owner', 'listen_group', 'listen_mode', and maybe some more) do not apply by reloading 'php-fpm.service' but require a proper restart.
Fixes #596

(#596) drop 'reload' in favour of 'restart'

---

REFERENCE.md
manifests/fpm/pool.pp
spec/classes/php_spec.rb
templates/fpm/pool.conf.erb

Add support for apparmor_hat directive. This allows a php-fpm binary contained by an Apparmor profile to switch to a more specific profile (`hat` in apparmor parlance) tailored to the FPM pool serving the request.
Here is an example of Apparmor profile including a hat called 'foo' for the pool serving a WordPress instance:
```
#include <tunables/global>
/usr/sbin/php-fpm7.2 {
#include <abstractions/base>
#include <abstractions/nameservice>
#include <abstractions/php>
capability chown,
capability dac_override,
capability kill,
capability setuid,
capability setgid,
capability sys_chroot,
capability sys_ptrace,
ptrace (trace) peer=/usr/sbin/php-fpm7.2//*,
/etc/php/7.2/fpm/php-fpm.conf  r,
/etc/php/7.2/fpm/pool.d/*.conf r,
/etc/ssl/openssl.cnf r,
/usr/sbin/php-fpm7.2 rmix,
owner …
```

Add apparmor_hat support to php::fpm::pool

---

manifests/fpm.pp
manifests/fpm/service.pp
manifests/init.pp

By default, this module uses a reload for the php-fpm service. This is
nice because it ensures that there is no downtime. But this is also bad
because certain configuration options, like unix socket owner/group will
only be changed during a restart.
Fixes: https://github.com/voxpupuli/puppet-php/issues/596
Replaces: https://github.com/voxpupuli/puppet-php/pull/597

php-fpm: Make service reload/restart configurable

---

.sync.yml
.travis.yml
manifests/globals.pp
metadata.json
spec/acceptance/php_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

php::globals: support Ubuntu 20.04 that ships php 7.4

---

manifests/globals.pp

Add Support for PHP 8
Fixes #612

Add PHP 8 Support

---

manifests/fpm/pool.pp

pm_start_servers=0 is a supported setting, can be used for on demand services.

Allow 0 for pm_start_servers

---

manifests/config/setting.pp
spec/classes/php_spec.rb

The code for `php::config::setting` permits passing `Undef` to force the `ini_setting` to be absent instead of present but the recent type change does not allow `Undef`.  This simply adds `Undef` as a valid type.

Allow a setting to be undef to force absent.

---

manifests/dev.pp
manifests/fpm/service.pp
manifests/globals.pp
manifests/init.pp
manifests/params.pp
spec/acceptance/php_spec.rb
spec/classes/php_fpm_service_spec.rb
spec/classes/php_repo_spec.rb
spec/classes/php_spec.rb
spec/defines/config_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

This PR allow to use puppet-php on unsupported environments.
Administrators can define a global php version like `php::globals::php_version: 8.1`. If defined, the automatic version discovery based on OS version will be disabled.
My use case: I want to run/test this module in a Ubuntu 22.04 dev environment.

Allow unsupported environments

---

manifests/dev.pp
manifests/fpm/service.pp
manifests/init.pp
manifests/params.pp
spec/acceptance/php_spec.rb
spec/classes/php_fpm_service_spec.rb
spec/classes/php_repo_spec.rb
spec/classes/php_spec.rb
spec/defines/config_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

Arch Linux: Fix package names and set correct php-fpm user (root -> http)

---

manifests/fpm/service.pp
spec/classes/php_fpm_service_spec.rb
spec/classes/php_repo_spec.rb
spec/classes/php_spec.rb
spec/defines/config_spec.rb
spec/defines/fpm_pool_spec.rb

newer distributions, like Arch Linux, do not ship `service` anymore. If systemd is the used init system, we should also use the systemd cli to reload a service. This is required to fix Arch Linux acceptance tests (besides #663 )

php-fpm: Reload service with systemd if available

---

manifests/repo/debian.pp
spec/classes/php_repo_debian_spec.rb

Remove dotdeb and sury repos overuse on Debian.
#436 looks like too far from readiness and probably we can use this PR now.
`assert_private()` was removed because tests couldn't run on private class and other php::repo classes aren't private also. Thank you!
Fixes #458

(#458) Remove dotdeb and sury repos overuse on Debian

---

manifests/fpm/service.pp

FreeBSD support for the FPM service broke in https://github.com/voxpupuli/puppet-php/commit/168d9b0e9a34cb58f7495b491a77b2b57d3e54ec, resulting in the following error message:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error:
No matching entry for selector parameter with value 'freebsd' (file: /etc/puppetlabs/code/environments/production/modules/php/manifests/fpm/service.pp, line: 35, column: 16) on node
```

fpm: fix FreeBSD support

---

manifests/fpm/config.pp

I am using php7.4 from sury on debian 10.
After every server reboot, this module creates the `/var/run/php-fpm` directory (which is not used by php-fpm) and triggers a reload, which resets all open connections to the php-fpm daemon.
This PR added an option to disable the managing of the `/var/run/php-fpm` directory

Add option to disable management of rundir

---

.fixtures.yml
README.md
manifests/globals.pp
manifests/params.pp
manifests/repo.pp
spec/classes/php_spec.rb

This PR adds support for ZendPHP on its [supported platforms](https://help.zend.com/zendphp/current/content/introduction/supported_platforms.htm).
This is accomplished by adding two parameters to `php::globals`:
- Optional[Enum['community', 'zend']] $flavor
- Optional[Hash] $zend_creds
```puppet
class { '::php::globals':
php_version => '8.1',
flavor      => 'zend',
}->
fpm       => true,
fpm_pools => {
www => {
listen => "127.0.0.1:9000",
},
}
}
```
```puppet
class { '::php::globals':
php_version => '5.6',
flavor      => 'zend',
zend_creds  => {
'username' => '<USERNAME>',
'password' => '<PASSWORD>',
},
}->
fpm       => true,
fpm_pools => {
www => {
listen => "127.0.0.1:9000",
},
}
}
```

Add ZendPHP support

---

manifests/fpm/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/php_spec.rb

I created the PR to parametrize the file permission for the php-fpm log directory.

Add class parameter `fpm_log_dir_mode` to customize the file permission of log directory

---

README.md

README: fix links, fix typos, remove outdated info

---

manifests/globals.pp
manifests/repo/debian.pp
metadata.json
spec/acceptance/php_spec.rb
spec/classes/php_repo_debian_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

Not much is changed for PHP in this upcoming release, except for the version of PHP shipped which is now 8.2

Add support for Debian 12 (bookworm)

---

.github/CONTRIBUTING.md
.github/labeler.yml
.github/release.yml
.github/workflows/labeler.yml
.github/workflows/release.yml
.msync.yml
.puppet-lint.rc
Gemfile
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_repo_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_rhscl_spec.rb
spec/defines/extension_spec.rb
spec/spec_helper.rb

Replace legacy facts

---

manifests/params.pp
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb

The service name on FreeBSD has been renamed from `php-fpm` to `php_fpm`.
Related upstream commit:
https://github.com/FreeBSD/freebsd-ports/commit/55272c38747e54876219ffcb73050514bfd21d0d
none

adopt new service name on FreeBSD

---

manifests/globals.pp
metadata.json
spec/acceptance/php_spec.rb
spec/classes/php_fpm_service_spec.rb
spec/classes/php_fpm_spec.rb
spec/classes/php_spec.rb
spec/defines/extension_spec.rb
spec/defines/fpm_pool_spec.rb

Add support for Ubuntu 24.04
Will add support for Ubuntu 24.04 with PHP 8.3

Add support for Ubuntu 24.04

---

manifests/params.pp

Download stable version of composer as opposed to snapshot
Fixes #575

Download stable version of composer as opposed to snapshot

---

.fixtures.yml
REFERENCE.md
manifests/extension/config.pp
manifests/init.pp
manifests/params.pp
spec/defines/extension_spec.rb

This ensures extension settings are configured in their respective Apache config files as well as the default cli config.
Current behavior:
Extension config file is created in the `apache2` subdirectory by `phpenmod`, but the settings defined in Puppet are not populated.
Tested on Ubuntu 20.04 + ondrej PHP 5.6 (environment that needed fixing), but should function on Debian + other versions, and the paths can be easily overridden.

add: support for apache-specific extension config on Debian
